import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { CreateProjectInput, GenerationProject } from "../types/project";
import { MEDIA_KIND_BY_TYPE } from "../types/project";
import { createId, randomSeed } from "../lib/ids";
import { titleFromPrompt } from "../lib/format";
import { deleteAsset } from "../lib/asset-store";
import { VIDEO_FPS } from "../lib/catalog";
import { SAMPLE_PROJECTS } from "../lib/samples";

export const PROJECT_STORAGE_KEY = "fluxframe-projects-v2";
export const MAX_PROJECTS = 400;

export interface ProjectState {
  projects: GenerationProject[];
  /** Ids currently being generated by the runner (not persisted). */
  activeJobIds: string[];
  hydrated: boolean;

  createProject: (input: CreateProjectInput) => GenerationProject;
  updateProject: (id: string, patch: Partial<GenerationProject>) => void;
  deleteProject: (id: string) => void;
  deleteProjects: (ids: string[]) => void;
  duplicateProject: (id: string) => GenerationProject | undefined;
  renameProject: (id: string, title: string) => void;
  toggleFavorite: (id: string) => void;
  getProject: (id: string) => GenerationProject | undefined;
  setJobActive: (id: string, active: boolean) => void;
  /** Marks queued/processing projects as failed after a reload (they cannot resume). */
  markInterruptedJobs: () => number;
  clearAllProjects: () => void;
  resetToSamples: () => void;
}

const ASSET_FIELDS: Array<keyof GenerationProject> = ["outputAssetId", "thumbnailAssetId", "sourceAssetId", "keyframeAssetId", "audioAssetId"];

function assetIdsOf(project: GenerationProject): string[] {
  return ASSET_FIELDS.map((field) => project[field]).filter((v): v is string => typeof v === "string");
}

/** Deletes assets that no remaining project references. Fire-and-forget. */
function releaseAssets(removed: GenerationProject[], remaining: GenerationProject[]): void {
  const referenced = new Set(remaining.flatMap(assetIdsOf));
  for (const project of removed) {
    for (const id of assetIdsOf(project)) {
      if (!referenced.has(id)) void deleteAsset(id);
    }
  }
}

export const useProjectStore = create<ProjectState>()(
  persist(
    (set, get) => ({
      projects: SAMPLE_PROJECTS,
      activeJobIds: [],
      hydrated: false,

      createProject: (input) => {
        const now = new Date().toISOString();
        const mediaKind = MEDIA_KIND_BY_TYPE[input.type];
        const project: GenerationProject = {
          id: createId("proj"),
          type: input.type,
          mediaKind,
          title: input.title?.trim() || titleFromPrompt(input.prompt, mediaKind === "image" ? "Untitled image" : "Untitled clip"),
          prompt: input.prompt,
          negativePrompt: input.negativePrompt?.trim() || undefined,
          model: input.model,
          aspectRatio: input.aspectRatio,
          width: input.width,
          height: input.height,
          duration: mediaKind === "video" ? (input.duration ?? 5) : undefined,
          fps: mediaKind === "video" ? (input.fps ?? VIDEO_FPS) : undefined,
          quality: input.quality ?? "high",
          status: "queued",
          progress: 0,
          stageMessage: "Queued",
          favorite: false,
          createdAt: now,
          updatedAt: now,
          seed: input.seed ?? randomSeed(),
          creditCost: input.creditCost ?? 0,
          sourceAssetId: input.sourceAssetId,
          audioAssetId: input.audioAssetId,
          cameraMotion: input.cameraMotion,
          motionStrength: input.motionStrength,
          marketing: input.marketing,
          lipsync: input.lipsync,
          tags: input.tags,
          origin: input.origin ?? "studio",
          parentId: input.parentId,
        };
        set((state) => ({ projects: [project, ...state.projects].slice(0, MAX_PROJECTS) }));
        return project;
      },

      updateProject: (id, patch) => {
        set((state) => ({
          projects: state.projects.map((p) => (p.id === id ? { ...p, ...patch, updatedAt: new Date().toISOString() } : p)),
        }));
      },

      deleteProject: (id) => get().deleteProjects([id]),

      deleteProjects: (ids) => {
        const idSet = new Set(ids);
        const removed = get().projects.filter((p) => idSet.has(p.id));
        const remaining = get().projects.filter((p) => !idSet.has(p.id));
        set({ projects: remaining, activeJobIds: get().activeJobIds.filter((jobId) => !idSet.has(jobId)) });
        releaseAssets(removed, remaining);
      },

      duplicateProject: (id) => {
        const source = get().getProject(id);
        if (!source) return undefined;
        const now = new Date().toISOString();
        const copy: GenerationProject = {
          ...source,
          id: createId("proj"),
          title: `${source.title} (copy)`,
          favorite: false,
          createdAt: now,
          updatedAt: now,
          origin: "remix",
          parentId: source.id,
          tags: source.tags?.filter((t) => t !== "sample"),
        };
        set((state) => ({ projects: [copy, ...state.projects] }));
        return copy;
      },

      renameProject: (id, title) => {
        const clean = title.trim();
        if (!clean) return;
        get().updateProject(id, { title: clean.slice(0, 80) });
      },

      toggleFavorite: (id) => {
        set((state) => ({ projects: state.projects.map((p) => (p.id === id ? { ...p, favorite: !p.favorite } : p)) }));
      },

      getProject: (id) => get().projects.find((p) => p.id === id),

      setJobActive: (id, active) => {
        set((state) => ({
          activeJobIds: active ? (state.activeJobIds.includes(id) ? state.activeJobIds : [...state.activeJobIds, id]) : state.activeJobIds.filter((jobId) => jobId !== id),
        }));
      },

      markInterruptedJobs: () => {
        const interrupted = get().projects.filter((p) => p.status === "queued" || p.status === "processing");
        if (interrupted.length === 0) return 0;
        const ids = new Set(interrupted.map((p) => p.id));
        set((state) => ({
          activeJobIds: [],
          projects: state.projects.map((p) =>
            ids.has(p.id)
              ? { ...p, status: "failed", progress: 0, stageMessage: undefined, errorMessage: "Interrupted by a page reload. Retry to run it again." }
              : p,
          ),
        }));
        return interrupted.length;
      },

      clearAllProjects: () => {
        const removed = get().projects;
        set({ projects: [], activeJobIds: [] });
        releaseAssets(removed, []);
      },

      resetToSamples: () => {
        const removed = get().projects;
        set({ projects: SAMPLE_PROJECTS, activeJobIds: [] });
        releaseAssets(removed, []);
      },
    }),
    {
      name: PROJECT_STORAGE_KEY,
      version: 2,
      partialize: (state) => ({ projects: state.projects }),
      onRehydrateStorage: () => (state) => {
        if (!state) return;
        state.markInterruptedJobs();
        useProjectStore.setState({ hydrated: true });
      },
    },
  ),
);

/** Selector helpers. */
export const selectProjectsOfType = (type: GenerationProject["type"]) => (state: ProjectState) => state.projects.filter((p) => p.type === type);
export const selectLatestCompleted = (type?: GenerationProject["type"]) => (state: ProjectState) =>
  state.projects.find((p) => p.status === "completed" && (!type || p.type === type));
export const selectActiveJobs = (state: ProjectState) => state.projects.filter((p) => state.activeJobIds.includes(p.id));
