/**
 * Shared Playwright helpers for the FluxFrame E2E suite.
 *
 * Typical spec setup (order matters: reset → seed → mock → goto):
 *
 *   test.beforeEach(async ({ page }) => {
 *     await resetStorage(page);
 *     await seedProjects(page, [sampleProjectFixture()]);
 *     await setCredits(page, 200);
 *     await mockPollinations(page);
 *     await gotoApp(page, "/create/image");
 *   });
 *
 * `resetStorage` and the seed helpers run once per browser tab (they are guarded by a
 * sessionStorage marker), so a `page.reload()` later in the test keeps whatever the app
 * persisted — persistence can be tested naturally.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { expect } from "@playwright/test";
import type { Locator, Page } from "@playwright/test";
import { AxeBuilder } from "@axe-core/playwright";
import type { GenerationProject } from "../src/types/project";

// ---- constants -------------------------------------------------------------------------------

/** Zustand persist keys (see src/store/*). */
export const STORAGE_KEYS = {
  projects: "fluxframe-projects-v2",
  credits: "fluxframe-credits-v2",
  ui: "fluxframe-ui-v1",
  account: "fluxframe-account-v1",
  auth: "higgsfield-auth-v1",
} as const;

/** IndexedDB database holding generated/uploaded blobs (src/lib/asset-store.ts). */
export const IDB_NAME = "fluxframe";

/** Below this width the sidebar is an off-canvas drawer opened by `mobile-nav-toggle`. */
export const MOBILE_BREAKPOINT = 768;

export const FIXTURES_DIR = fileURLToPath(new URL("./fixtures/", import.meta.url));

function fixturePath(preferred: string, fallback: string): string {
  const primary = join(FIXTURES_DIR, preferred);
  return existsSync(primary) ? primary : join(FIXTURES_DIR, fallback);
}

/** Absolute paths of the binary fixtures generated by `e2e/fixtures/make-fixtures.py`. */
export const FIXTURES = {
  /** 640x360 gradient with a bright disc — keyframe for Video/Cinema studios. */
  keyframe: fixturePath("keyframe.jpg", "keyframe.png"),
  /** 512x640 face-like portrait — LipSync studio source. */
  portrait: fixturePath("portrait.jpg", "portrait.png"),
  /** 512x512 rounded "bottle" on transparent background — Marketing packshot. */
  packshot: join(FIXTURES_DIR, "packshot.png"),
  /** 3 s, 16 kHz mono WAV with 0.25 s tone bursts — LipSync audio. */
  speech: join(FIXTURES_DIR, "speech.wav"),
} as const;

/** Output media rendered by `OutputCanvas` once a job of that studio has completed. */
export const OUTPUT_MEDIA_SELECTOR =
  '[data-testid="output-canvas"] [data-testid="output-image"], [data-testid="output-canvas"] [data-testid="output-video"]';

const RESET_MARKER = "__fluxframe_e2e_reset__";
const SEED_MARKER_PREFIX = "__fluxframe_e2e_seed__:";
const CORS_HEADERS = { "access-control-allow-origin": "*", "cache-control": "no-store" };

function mimeTypeFor(file: string): string {
  return file.endsWith(".png") ? "image/png" : "image/jpeg";
}

let keyframeCache: Buffer | undefined;
function keyframeBytes(): Buffer {
  keyframeCache ??= readFileSync(FIXTURES.keyframe);
  return keyframeCache;
}

// ---- network -----------------------------------------------------------------------------------

export interface MockPollinationsOptions {
  /** Artificial latency (ms) before each successful image response. */
  delayMs?: number;
  /** Number of leading requests that fail with `status` before responses succeed. */
  failTimes?: number;
  /**
   * HTTP status for the failing requests. Default 403 = Pollinations rate limit, which makes
   * the client back off for 15 s before retrying; use 500 for a quick (1.5 s) retry path.
   */
  status?: number;
}

export interface PollinationsMock {
  /** Every requested `https://image.pollinations.ai/...` URL, in order. */
  requests: string[];
}

/**
 * Serves the keyframe fixture for every Pollinations image request so specs are fast,
 * deterministic and offline-safe (Google Fonts requests are aborted as well).
 */
export async function mockPollinations(page: Page, options: MockPollinationsOptions = {}): Promise<PollinationsMock> {
  const { delayMs = 0, failTimes = 0, status = 403 } = options;
  const mock: PollinationsMock = { requests: [] };
  let failuresLeft = failTimes;

  await page.route("https://fonts.googleapis.com/**", (route) => route.abort());
  await page.route("https://fonts.gstatic.com/**", (route) => route.abort());

  await page.route("https://image.pollinations.ai/**", async (route) => {
    mock.requests.push(route.request().url());
    if (failuresLeft > 0) {
      failuresLeft -= 1;
      await route.fulfill({ status, contentType: "text/plain", body: "rate limited", headers: CORS_HEADERS }).catch(() => undefined);
      return;
    }
    if (delayMs > 0) await new Promise((resolve) => setTimeout(resolve, delayMs));
    await route
      .fulfill({ status: 200, contentType: mimeTypeFor(FIXTURES.keyframe), body: keyframeBytes(), headers: CORS_HEADERS })
      .catch(() => undefined); // page may have closed while we were delaying
  });

  return mock;
}

// ---- navigation --------------------------------------------------------------------------------

export function isMobileViewport(page: Page): boolean {
  const viewport = page.viewportSize();
  return viewport !== null && viewport.width < MOBILE_BREAKPOINT;
}

/**
 * Navigates to an app route and waits for the shared Higgsfield-style header.
 */
export async function gotoApp(page: Page, path = "/"): Promise<void> {
  await page.goto(path);
  await expect(page.getByTestId("landing-logo")).toBeVisible();
}

// ---- storage -----------------------------------------------------------------------------------

/**
 * Clears localStorage/sessionStorage and deletes the "fluxframe" IndexedDB database before the
 * app boots. Register it before `gotoApp` and before any seed helper. Runs once per tab.
 */
export async function resetStorage(page: Page): Promise<void> {
  await page.addInitScript(
    ({ marker, dbName, authKey, authValue }) => {
      try {
        if (window.sessionStorage.getItem(marker)) return; // already reset in this tab
        window.localStorage.clear();
        window.localStorage.setItem(authKey, authValue);
        window.sessionStorage.clear();
        window.sessionStorage.setItem(marker, "1");
        window.indexedDB.deleteDatabase(dbName);
      } catch {
        // Storage is unavailable on this document (e.g. about:blank); nothing to reset.
      }
    },
    {
      marker: RESET_MARKER,
      dbName: IDB_NAME,
      authKey: STORAGE_KEYS.auth,
      authValue: JSON.stringify({ state: { users: [{ id: "e2e-user", name: "Test Creator", email: "test@example.com", passwordHash: "c638833f69bbfb3c267afa0a74434812436b8f08a81fd263c6be6871de4f1265", createdAt: "2026-01-01T00:00:00.000Z" }], currentUserId: "e2e-user" }, version: 0 }),
    },
  );
}

async function seedLocalStorage(page: Page, key: string, value: unknown): Promise<void> {
  await page.addInitScript(
    ({ key, json, marker }) => {
      try {
        if (window.sessionStorage.getItem(marker)) return; // seeded once per tab
        window.localStorage.setItem(key, json);
        window.sessionStorage.setItem(marker, "1");
      } catch {
        // Storage is unavailable on this document; nothing to seed.
      }
    },
    { key, json: JSON.stringify(value), marker: `${SEED_MARKER_PREFIX}${key}` },
  );
}

/** Seeds the project library (Zustand persist format). Pass `[]` for an empty library. */
export async function seedProjects(page: Page, projects: unknown[]): Promise<void> {
  await seedLocalStorage(page, STORAGE_KEYS.projects, { state: { projects }, version: 2 });
}

/** Seeds the credit balance (free plan, empty history). */
export async function setCredits(page: Page, balance: number): Promise<void> {
  await seedLocalStorage(page, STORAGE_KEYS.credits, {
    state: { balance, lifetimeGranted: balance, lifetimeSpent: 0, planId: "free", history: [] },
    version: 2,
  });
}

export interface StorageSeed {
  projects?: unknown[];
  credits?: number;
}

/** Convenience wrapper around `seedProjects` + `setCredits`. */
export async function seedStorage(page: Page, seed: StorageSeed): Promise<void> {
  if (seed.projects) await seedProjects(page, seed.projects);
  if (seed.credits !== undefined) await setCredits(page, seed.credits);
}

// ---- UI assertions -----------------------------------------------------------------------------

export type ToastType = "success" | "error" | "warning" | "info";

/** Expects a toast containing `text` (optionally of a given `data-toast-type`) and returns it. */
export async function expectToast(page: Page, text: string | RegExp, type?: ToastType): Promise<Locator> {
  const toast = page.getByTestId("toast").filter({ hasText: text }).first();
  await expect(toast).toBeVisible();
  if (type) await expect(toast).toHaveAttribute("data-toast-type", type);
  return toast;
}

/**
 * Waits for the studio's active job to finish: no `queue-panel` in a cancellable
 * (queued/processing) state and an image/video rendered inside `output-canvas`.
 * Call it right after clicking `generate-button`. Throws early when the job fails.
 */
export async function waitForJobComplete(page: Page, timeoutMs = 45_000): Promise<void> {
  const queuePanel = page.getByTestId("queue-panel");
  const cancelButton = queuePanel.getByTestId("queue-cancel").first();
  const retryButton = queuePanel.getByTestId("queue-retry").first();
  const output = page.locator(OUTPUT_MEDIA_SELECTOR).first();

  // Let the job register first so an output from an earlier run is not mistaken for this one.
  await cancelButton.waitFor({ state: "visible", timeout: 5_000 }).catch(() => undefined);

  const result: { state: "pending" | "completed" | "failed"; detail: string } = { state: "pending", detail: "" };
  await expect
    .poll(
      async () => {
        if (await retryButton.isVisible().catch(() => false)) {
          result.detail = (await queuePanel.first().innerText().catch(() => "")).replace(/\s+/g, " ").trim();
          result.state = "failed";
        } else if (await cancelButton.isVisible().catch(() => false)) {
          result.state = "pending";
        } else {
          result.state = (await output.isVisible().catch(() => false)) ? "completed" : "pending";
        }
        return result.state;
      },
      { timeout: timeoutMs, intervals: [250, 500, 1_000], message: "Timed out waiting for the generation job to finish" },
    )
    .not.toBe("pending");

  if (result.state === "failed") throw new Error(`Generation failed: ${result.detail || "see the queue panel"}`);
  await expect(output).toBeVisible();
}

/** Uploads a fixture through a `Dropzone` (its hidden input is `${testId}-input`). */
export async function uploadToDropzone(page: Page, dropzoneTestId: string, filePath: string): Promise<void> {
  await expect(page.getByTestId(dropzoneTestId)).toBeVisible();
  await page.getByTestId(`${dropzoneTestId}-input`).setInputFiles(filePath);
}

// ---- accessibility -----------------------------------------------------------------------------

export interface CheckA11yOptions {
  /** Restrict the scan to one region (CSS selector). */
  include?: string;
  /** Extra selectors to exclude; `[data-testid="canvas-root"]` is always excluded. */
  exclude?: string[];
  /** Axe rule ids to disable for this check (use sparingly, with a comment). */
  disableRules?: string[];
}

/** Runs axe (WCAG 2.0 A/AA) and fails on any critical or serious violation. */
/**
 * Waits for entrance animations to finish before an axe scan.
 *
 * Axe computes colour contrast by blending the foreground with its ancestors'
 * *current* opacity. Page roots mount with `animate-fade-in` (180 ms), so a scan
 * that starts mid-fade reports contrast for a half-transparent element: zinc-400
 * on surface-0 measures 2.86:1 during the fade and 7.6:1 once it settles. That
 * produces page-wide phantom violations. Infinite animations (spinners, pulses)
 * never finish, so they are ignored.
 */
export async function settleAnimations(page: Page, timeoutMs = 5_000): Promise<void> {
  await page
    .waitForFunction(
      () =>
        document.getAnimations().every((animation) => {
          const iterations = animation.effect?.getComputedTiming().iterations ?? 1;
          return iterations === Infinity || animation.playState !== "running";
        }),
      undefined,
      { timeout: timeoutMs },
    )
    .catch(() => {
      /* A stubborn animation must not fail the scan; axe still runs below. */
    });
}

export async function checkA11y(page: Page, options: CheckA11yOptions = {}): Promise<void> {
  await settleAnimations(page);
  let builder = new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa"]).exclude('[data-testid="canvas-root"]');
  for (const selector of options.exclude ?? []) builder = builder.exclude(selector);
  if (options.include) builder = builder.include(options.include);
  if (options.disableRules?.length) builder = builder.disableRules(options.disableRules);

  const { violations } = await builder.analyze();
  const blocking = violations
    .filter((violation) => violation.impact === "critical" || violation.impact === "serious")
    .map((violation) => ({
      id: violation.id,
      impact: violation.impact,
      help: violation.help,
      nodes: violation.nodes.map((node) => node.target.join(" ")),
    }));

  const message = blocking.length
    ? `Axe found ${blocking.length} critical/serious violation(s) on ${page.url()}:\n` +
      blocking.map((v) => `  - ${v.id} [${v.impact}] ${v.help}\n      ${v.nodes.join("\n      ")}`).join("\n")
    : "";
  expect(blocking, message).toEqual([]);
}

// ---- fixtures ----------------------------------------------------------------------------------

/** A completed image project (uses a bundled showcase image) for seeding the library. */
export function sampleProjectFixture(overrides: Partial<GenerationProject> = {}): GenerationProject {
  const timestamp = new Date(Date.now() - 60 * 60 * 1000).toISOString();
  return {
    id: "proj_e2e_valkyrie",
    type: "image",
    mediaKind: "image",
    title: "Obsidian Valkyrie",
    prompt:
      "Cinematic portrait of a cybernetic warrior in obsidian armour with bioluminescent blue trim, 85mm lens, volumetric smoke, dramatic rim lighting",
    model: "flux-realism-v2",
    aspectRatio: "16:9",
    width: 1024,
    height: 576,
    quality: "high",
    status: "completed",
    progress: 100,
    stageMessage: "Completed",
    outputUrl: "/showcase/valkyrie.jpg",
    thumbnailUrl: "/showcase/valkyrie.jpg",
    outputMimeType: "image/jpeg",
    favorite: false,
    createdAt: timestamp,
    updatedAt: timestamp,
    completedAt: timestamp,
    seed: 8492041,
    creditCost: 5,
    providerSource: "pollinations",
    providerDetail: "Generated with the image pipeline",
    renderMs: 4200,
    tags: ["e2e"],
    origin: "studio",
    ...overrides,
  };
}
